services:
  kybe-backend:
    image: reg.kybe.xyz/kybe-pub/kybe-backend:latest
    container_name: kybe-backend
    ports:
      - "3000:3000"
      - "2222:2222"
    restart: unless-stopped
    volumes:
      - ./backend/config:/opt/backend/config
