name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  LOCAL_TAG: kybe-backend:latest
  REMOTE_TAG: reg.kybe.xyz/kybe-pub/kybe-backend
  REGISTRY_URL: reg.kybe.xyz
  TAG: ${{ github.sha }}

jobs:
  deploy:
    name: Build, Push & Deploy Backend
    runs-on: self-hosted
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest@sha256:c710431fbad9eb3bcb102d04e5ff74fbd0ce6e383f78afebfb3770a1a817fdf9

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: https://github.com/cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Setup Attic
        id: attic
        run: |
          nix profile install .#ci
          attic login main https://attic.kybe.xyz/main ${{ secrets.ATTIC_KEY }}
          attic use main

      - name: Build image
        run: nix build .#image -L -v --no-update-lock-file

      - name: Load image
        run: docker load < ./result

      - name: Tag Docker image
        run: docker tag ${{ env.LOCAL_TAG }} ${{ env.REMOTE_TAG }}

      - name: Log in to private registry
        uses: https://github.com/docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Push image
        run: docker push ${{ env.REMOTE_TAG }}

      - name: Copy docker-compose.yml to server
        uses: https://github.com/appleboy/ssh-action@068c0c7a4e59a5ae12fb7cb454b05735d830c82b # master
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.RUNNER_SSH_KEY }}
          overwrite: true
          source: "docker-compose.yml"
          target: "/opt/backend/"

      - name: Deploy to production server
        uses: https://github.com/appleboy/ssh-action@068c0c7a4e59a5ae12fb7cb454b05735d830c82b # master
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.RUNNER_SSH_KEY }}
          script: |
            echo "${{ secrets.REGISTRY_PASS }}" | docker login ${{ env.REGISTRY_URL }} -u "${{ vars.REGISTRY_USER }}" --password-stdin

            cd /opt/backend
            docker compose pull
            docker compose up -d --force-recreate --remove-orphans
          envs: REGISTRY_URL,REGISTRY_USER

      - name: Push to Attic
        if: ${{ steps.attic.conclusion == 'success' }}
        run: attic push main --ignore-upstream-cache-filter -j 64 $(ls -d /nix/store/*/)
